import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT_FILE = path.join(ROOT, 'src/generated/templates.ts')

const BINARY_EXTENSIONS = new Set(['.ico', '.png', '.jpg', '.jpeg', '.gif', '.webp', '.woff', '.woff2', '.ttf', '.eot'])

interface TemplateTree {
	[filePath: string]: { content: string; encoding: 'utf8' | 'base64' }
}

function walkDir(dir: string, prefix = ''): TemplateTree {
	const tree: TemplateTree = {}

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const fullPath = path.join(dir, entry.name)
		const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name

		if (entry.isDirectory()) {
			Object.assign(tree, walkDir(fullPath, relativePath))
		} else {
			const ext = path.extname(entry.name).toLowerCase()
			if (BINARY_EXTENSIONS.has(ext)) {
				tree[relativePath] = {
					content: fs.readFileSync(fullPath).toString('base64'),
					encoding: 'base64',
				}
			} else {
				tree[relativePath] = {
					content: fs.readFileSync(fullPath, 'utf8'),
					encoding: 'utf8',
				}
			}
		}
	}

	return tree
}

function generate() {
	const templateDirs = fs
		.readdirSync(ROOT)
		.filter((name) => name.startsWith('template-') && fs.statSync(path.join(ROOT, name)).isDirectory())
		.sort()

	const templates: Record<string, TemplateTree> = {}

	for (const dir of templateDirs) {
		const templateName = dir.replace('template-', '')
		templates[templateName] = walkDir(path.join(ROOT, dir))
	}

	const lines: string[] = [
		'// Auto-generated by scripts/embed-templates.ts — do not edit',
		'',
		'export interface TemplateFile {',
		'  content: string',
		'  encoding: "utf8" | "base64"',
		'}',
		'',
		'export type TemplateTree = Record<string, TemplateFile>',
		'',
		`export const templates: Record<string, TemplateTree> = ${JSON.stringify(templates, null, 2)} as const`,
		'',
	]

	fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
	fs.writeFileSync(OUT_FILE, lines.join('\n'))

	const totalFiles = Object.values(templates).reduce((sum, t) => sum + Object.keys(t).length, 0)
	console.log(`Embedded ${totalFiles} files from ${templateDirs.length} templates → ${path.relative(ROOT, OUT_FILE)}`)
}

generate()
